# Generated by Django 3.1.2 on 2021-02-10 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210210_1431'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
